// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjgvvtpgjgknanmtvdyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qZ3Z2dHBnamdrbmFubXR2ZHlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NTE4MTMsImV4cCI6MjA2MjUyNzgxM30.2x14AwgByCHoCKfbEcaReXhcBmDZPKIWGaLBfGlB_tc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
